#! /bin/sh

####################
###    bspwmrc   ###
####################

#
## - Mouse/Pointer

# Set cursor to left pointer
xsetroot -cursor_name left_ptr

# Set mouse 1 to move floating windows
bspc config pointer_action1 move

# Set mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

# Set mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner

#
## - Services

# nm-applet
nm-applet &

# Desktop dbus session (GNOME keyring)
dbus-run-session -- sh

# GNOME keyring
eval $(gnome-keyring-daemon --start) export SSH_AUTH_SOCK

# Start keybindings
sxhkd &

# Set screen resolution
autorandr --change

# Set wallpaper
feh --bg-fill $HOME/Pictures/Backgrounds/* --randomize --bg-fill $HOME/Pictures/Backgrounds/*

# Start picom
if ! pgrep -x "picom" > /dev/null
then
	picom -b  --experimental-backends
fi


# Start the upower-notify daemon
if ! pgrep -x "upower-notify" > /dev/null
then
	upower-notify &
fi

# Start polybar
zsh ~/.config/polybar/launch.sh

#
## - Workspaces
bspc monitor DP-1-2-2 -d 1 2 3 4 5
bspc monitor DP-1-2-1 -d 6 7 8 9 0
bspc monitor eDP-1-1 -d 1 2 3 4 5
bspc monitor eDP-1 -d 1 2 3 4 5

#
## - Rules
bspc rule -a 'jetbrains-idea:torchv2*' desktop=1 follow=on
bspc rule -a 'jetbrains-idea:torch-api*' desktop=2 follow=off
bspc rule -a 'jetbrains-idea:torch-files*' desktop=2 follow=off
bspc rule -a 'Polybar tray window' layer=above # Keep the Polybar tray above everything else
bspc rule -a tide.exe state=floating focus=off follow=on
#
## - Padding
bspc config top_padding 0
bspc config bottom_padding 25
bspc config left_padding 5
bspc config right_padding 5

#
## - Border
bspc config border_width 4
bspc config focused_border_color '#006ee6'

#
## - Misc.
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
wmname LG3D # Fixes IntelliJ IDEA/Java applications


### END
xdo raise -a 'Polybar tray window'

