#! /bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

sxhkd &

# Set screen resolution
#xrandr --output eDP-1-1 --off --output DP-1-1 --off --output DP-1-2 --off --output HDMI-1-1 --off --output DP-1-2-1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1-2-2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1-2-3 --off
autorandr --change

# Set wallpaper
feh --bg-fill $HOME/Pictures/Backgrounds/* --randomize --bg-fill $HOME/Pictures/Backgrounds/*


# Start picom
picom -b

# Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner


# panel
zsh ~/.config/polybar/launch.sh

# Add twerkspaces
bspc monitor DP-1-2-2 -d 1 2 3 4 5
bspc monitor DP-1-2-1 -d 6 7 8 9 0
bspc monitor eDP-1-1 -d 1 2 3 4 5

# Rules
bspc rule -a 'jetbrains-idea:torchv2*' desktop=1 follow=on
bspc rule -a 'jetbrains-idea:torch-api*' desktop=2 follow=off
bspc rule -a 'jetbrains-idea:torch-files*' desktop=2 follow=off

# Gap n border

bspc config window_gap 1
bspc config border_width 2


bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true


bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Bullshit
wmname LG3D


# Stolen form Gk, because I'm too stupid to actually learn how to use chwb2
outer='0x20202A'   # outer
inner1='0x414560'  # focused
inner2='0x2c2e3e'  # normal

targets() {
	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

draw() { chwb2 -I "$inner" -O "$outer" -i "2" -o "9" $* |:; }

# initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
	while read -r _; do
		v=$(echo $(xdo id -N Firefox))
		v=${v// /\\|}
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets  normal)"
	done

nm-applet &


